export interface Address {
  addressLine: string;
  city: string;
  state: string;
}
export interface InstitutionLocation{
  name:string,
  coord:any[],
  address:string
}
export interface Institution {
  address: Address;
  name: string;
  type: string;
  specialities: string[];
  medicalInsurance?: string[];
}
export interface Questionary{
pain:boolean,
quantityPain?:number,
regionOfPain?:string[],
vomit:boolean,
breathDificulty:boolean,
painOnBreath?:boolean,
fever:string,
feverQuantity?:number,
bleeding:boolean,
stopBleeding?:boolean,
nausea:boolean
}
export class InstitutionData {
  public institution: Institution[] = [
    {
      name: "Hospital Municipal Doutor Alexandre Zaio",
      address: {
        addressLine: "Rua Alves Maldonado, 128 - Vila Nhocuné",
        city: "São Paulo",
        state: "SP",
      },
      type: "public",

      specialities: ["Clínica Médica", "Pediatria"],
    },
    {
      name: "Hospital Municipal Dr José Soares Hungria",
      address: {
        addressLine: "Rua Menotti Laudísio, 100 - Pirituba",
        city: "São Paulo",
        state: "SP",
      },
      type: "public",

      specialities: [
        "Clínica Médica",
        "Clínica Geral",
        "Ortopedia Geral",
        "Obstetrícia",
        "Ginecologia",
        "Pediatria",
        "Psiquiatria",
      ],
    },
    {
      name:
        "Hospital Municipal Dr Gilson de Cássia Marques de Carvalho - Vila Santa Catarina",
      address: {
        addressLine: "Avenida Santa Catarina, 2785 - Vila Mascote",
        city: "São Paulo",
        state: "SP",
      },
      type: "public",

      specialities: [
        "Clínica Médica",
        "Clínica Geral",
        "Pediatria",
        "Ginecologia",
        "Obstetrícia",
        "Neonatologia",
        "Oncologia Clínica",
        "Psiquiatria",
      ],
    },
    {
      name: "Hospital Municipal Vereador José Storopolli",
      address: {
        addressLine: "Rua Francisco Franganiello, 127 - Pq Novo Mundo",
        city: "São Paulo",
        state: "SP",
      },
      type: "public",

      specialities: [
        "Clínica Médica",
        "Pediatria",
        "Psiquiatria",
        "Ortopedia Geral",
      ],
    },
    {
      name: "Unidade de Pronto Atendimento Vila Santa Catarina - UPA",
      address: {
        addressLine: "Rua Cidade de Bagdá, 529 - Vila Santa Catarina",
        city: "São Paulo",
        state: "SP",
      },
      type: "public",

      specialities: ["Clínica Médica", "Pediatria", "Ortopedia Geral"],
    },
    {
      name: "Hospital Municipal Dr Moyses Deutsch - M` Boi Mirim",
      address: {
        addressLine: "Estrada do M Boi Mirim, 5203 - Jd Angela",
        city: "São Paulo",
        state: "SP",
      },
      type: "public",

      specialities: [
        "Clínica Médica",
        "Clínica Geral",
        "Pediatria",
        "Ginecologia",
        "Obstetrícia",
        "Neonatologia",
        "Infectologia",
        "Psiquiatria",
      ],
    },
    {
      name: "Hospital Municipal Dr. Benedicto Montenegro",
      address: {
        addressLine: "Rua Antonio Lazaro, 226 - Jardim Iva",
        city: "São Paulo",
        state: "SP",
      },
      type: "public",
      specialities: [
        "Clínica Médica",
        "Pediatria",
        "Ortopedia Geral",
        "Psiquiatria",
        "Odontologia emergencial",
      ],
    },
    {
      name: "Hospital Municipal Profº. Dr. Waldomiro de Paula",
      address: {
        addressLine: "Rua Augusto Carlos Bauman , 1074 - Itaquera",
        city: "São Paulo",
        state: "SP",
      },
      type: "public",
      specialities: [
        "Clínica Médica",
        "Pediatria",
        "Ginecologia",
        "Obstetrícia",
        "Neonatologia",
        "Psiquiatria",
        "Covid-19",
      ],
    },
    {
      name: "Hospital Municipal Dr. Cármino Caricchio",
      address: {
        addressLine: "Avenida Celso Garcia, 4815 - Tatuapé",
        city: "São Paulo",
        state: "SP",
      },
      type: "public",
      specialities: [
        "Nefrologia",
        "Gastroenterologia",
        "Neurologia Clínica",
        "Cardiologia",
        "Geriatria",
        "Hematologia",
        "Pediatria",
        "Neurocirurgia",
        "Bucomaxilo Facial",
        "Traumatologia",
      ],
    },
    {
      name: "Hospital Municipal Dr. Fernando Mauro Pires da Rocha",
      address: {
        addressLine: "Estrada de Itapecerica, 1661 - Vila Maracanã",
        city: "São Paulo",
        state: "SP",
      },
      type: "public",
      specialities: [
        "Clínica Médica",
        "Neurologia Clínica",
        "Ortopedia Geral",
        "Pediatria",
        "Ginecologia",
        "Obstetrícia",
        "Neonatologia",
        "Infectologia",
        "Psiquiatria",
        "Bucomaxilo Facial",
        "Fisioterapia",
        "Nutrologia",
        "Dermatologia",
        "Cardiologia",
        "Endocrinologia",
      ],
    },
    {
      name: "Hospital Municipal Dr. Ignácio Proença de Gouvêa",
      address: {
        addressLine: "Rua Juventus, 562 – Parque da Mooca",
        city: "São Paulo",
        state: "SP",
      },
      type: "public",
      specialities: [
        "Clínica Médica",
        "Pediatria",
        "Ortopedia Geral",
        "Tocoginecologia",
      ],
    },
    {
      name: "Hospital Municipal Dr. Arthur Ribeiro de Saboya",
      address: {
        addressLine: "Avenida Francisco de Paula Quintanilha Ribeiro, 860",
        city: "São Paulo",
        state: "SP",
      },
      type: "public",
      specialities: [
        "Covid-19",
        "Clínica Médica",
        "Clínica Geral",
        "Ginecologia",
        "Traumatologia",
        "Ortopedia Geral",
        "Pediatria",
        "Neurocirurgia",
        "Psiquiatria",
        "Bucomaxilo Facial",
        "Oftalmologia",
      ],
    },
    {
      name: "Hospital Municipal Profº. Dr. Alípio Corrêa Netto",
      address: {
        addressLine: "Alameda Rodrigo de Brum 1989 – Ermelino Matarazzo",
        city: "São Paulo",
        state: "SP",
      },
      type: "public",
      specialities: [
        "Clínica Médica",
        "Clínica Geral",
        "Ortopedia Geral",
        "Neurocirurgia",
        "Traumatologia",
        "Ginecologia",
        "Obstetrícia",
        "Psiquiatria",
        "Pediatria",
        "Neonatologia",
        "Bucomaxilo Facial",
        "Oftalmologia",
      ],
    },
    {
      name: "Hospital Municipal Tide Setúbal",
      address: {
        addressLine: "Rua Dr. José Guilherme Eiras, 123 – São Miguel Paulista",
        city: "São Paulo",
        state: "SP",
      },
      type: "public",
      specialities: [
        "Clínica Médica",
        "Clínica Geral",
        "Ortopedia Geral",
        "Neurocirurgia",
        "Traumatologia",
        "Ginecologia",
        "Obstetrícia",
        "Psiquiatria",
        "Pediatria",
        "Neonatologia",
        "Bucomaxilo Facial",
        "Oftalmologia",
      ],
    },
    {
      name: "Hospital Santa Clara",
      address: {
        addressLine: "Rua Joaquim Marra, 138 - Vila Matilde",
        city: "São Paulo",
        state: "SP",
      },
      type: "private",
      medicalInsurance: [
        "Amil Saúde",
        "Abet",
        "AMR",
        "ASSEFAZ",
        "BioVida",
        "Bradesco Saúde",
        "GS",
        "Mapfre",
        "MediSanitas",
        "Mediservice",
        "Porto Seguro",
        "Santaris",
        "Sao Miguel",
        "Next Seisa",
        "Saude Sistema",
        "Transmontano Saude",
        "Unimed Rio",
        "UniHosp",
      ],
      specialities: [
        "Clínica Médica",
        "Ortopedia Geral",
        "Psicologia",
        "Dermatologia",
        "Ginecologista",
        "Endocrinologia",
        "Geriatria",
        "Neurocirurgia",
        "Neurologia Clínica",
      ],
    },
    {
      name: "Hospital Santa Marcelina",
      address: {
        addressLine: "Rua Santa Marcelina, 177 – Itaquera – São Paulo",
        city: "São Paulo",
        state: "SP",
      },
      type: "both",
      specialities: [
        "Alergologia/Imunologia",
        "Angiologia (Vascular)",
        "Anestesiologia",
        "Cardiologia",
        "Clínica Médica",
        "Coloproctologia",
        "Dermatologia",
        "Endocrinologia",
        "Especialidade da Dor",
        "Esteticista",
        "Fisioterapia",
        "Fonoaudiologia",
        "Gastroenterologia",
        "Geriatria",
        "Ginecologia",
        "Obstetrícia",
        "Hematologia",
        "Hepatologia",
        "Infectologia",
        "Mastologia",
        "Nefrologia",
        "Neurologia Cirúrgica",
        "Neurologia Clínica",
        "Nutricionista",
        "Oftalmologia",
        "Oncologia Clínica",
        "Ortopedia Geral",
        "Traumatologia",
        "Otorrinolaringologia",
        "Pediatria",
        "Pneumologia",
        "Psicologia",
        "Psiquiatria",
        "Proctologia",
        "Radioterapia",
        "Reumatologia",
        "Reflexologia",
        "Urologia",
      ],
      medicalInsurance: [
        "Aeronáutica",
        "Allianz",
        "Amil Saúde",
        "Bradesco Saúde",
        "Cabesp",
        "Caixa Econômica",
        "Care Plus",
        "Central Nacional Unimed",
        "Clínica Médica Confiamed",
        "Cnen Ipen",
        "Economus",
        "Funcesp",
        "Gama Saúde",
        "Golden Cross",
        "Good-Life",
        "Hbc-Saúde",
        "Intermédica Notre Dame",
        "Irmãs Missionárias",
        "Life Empresarial",
        "Mapfre",
        "Mediservice",
        "Metrus",
        "Omint",
        "Porto Seguro",
        "Postal Saúde",
        "Samed",
        "Santa Casa de São José Dos Campos",
        "Santa Casa de Santos",
        "São Cristóvão",
        "Seguros Unimed",
        "Sompo Saúde",
        "Sul América",
        "Unimed Belém",
      ],
    },
    {
      name: "Hospital Santo Expedito",
      address: {
        addressLine: "Avenida Jacu Pêssego, 2705 - Itaquera",
        city: "São Paulo",
        state: "SP",
      },
      type: "private",
      medicalInsurance: [
        "AMR",
        "Amil Saúde",
        "Porto Seguro",
        "São Miguel",
        "Garantia",
        "Garantia Adventista",
        "Transmontano Saude",
        "BioVida",
        "AXA – PORTOMED",
        "MEDSERVICE",
        "TOTAL MEDCARE",
        "AMEPLAN",
        "Unimed Rio",
        "Intermédica Notre Dame",
        "UniHosp",
        "Sompo Saúde",
        "METROPOLE",
        "MediSanitas",
        "Prevent Sênior",
        "CLASSES LABORIOSAS",
      ],
      specialities: [
        "Clínica Médica",
        "Ortopedia Geral",
        "Psicologia",
        "Dermatologia",
        "Pediatria",
        "Endocrinologia",
        "Geriatria",
      ],
    },
    {
      name: "Hospital Paranaguá",
      address: {
        addressLine: "Avenida Paranagua, 808 - Ermelino Matarazzo",
        city: "São Paulo",
        state: "SP",
      },
      type: "private",
      medicalInsurance: [
        "Ameplan",
        "Amil Saúde",
        "Assistence",
        "BioSaude",
        "Bradesco Saúde",
        "CLASSES LABORIOSAS",
        "Cruz Azul",
        "Economus",
        "Funcesp",
        "GEAP Saude",
        "Golden Cross",
        "Intermédica Notre Dame",
        "Porto Seguro",
        "Metrus",
        "Mediservice",
        "Sompo Saúde",
        "Central Nacional Unimed",
        "Sepaco",
        "SPTrans",
        "Unimed Fesp",
        "Seguros Unimed",
      ],
      specialities: ["Clínica Médica", "Ortopedia Geral", "Pediatria"],
    },
    {
      name: "Hospital Sagrada Família",
      address: {
        addressLine: "Rua Arapoca, 154 - Vila Formosa",
        city: "São Paulo",
        state: "SP",
      },
      type: "private",
      medicalInsurance: [
        "Allianz",
        "AWP",
        "ASSIST CARD",
        "Bradesco Saúde",
        "APEOESP",
        "CAASP",
        "MAPFRE",
        "MONDIAL",
        "Porto Seguro",
        "Postal Saúde",
      ],
      specialities: [
        "Anestesiologia",
        "Angiologia",
        "Cirurgia do Aparelho Digestivo",
        "Cirurgia Vascular",
        "Fisioterapia",
        "Gastroenterologia",
        "Ginecologia",
        "Obstetrícia",
        "Medicina do Trabalho",
        "Neurocirurgia",
        "Neurologia Clínica",
        "Nutrição",
        "Ortopedia Geral",
        "Traumatologia",
        "Radiologia",
        "Pediatria",
        "Proctologia",
        "Urologia",
      ],
    },
    {
      name: "Hospital Vitória",
      address: {
        addressLine: "Avenida Vereador Abel Ferreira, 1900, Jardim Anália Franco",
        city: "São Paulo",
        state: "SP",
      },
      type: "private",
      medicalInsurance: [
        "Allianz",
        "Amil Saúde",
        "Abet",
        "ASSEFAZ",
        "Afresp",
        "ASSIST CARD",
        "Blue Life",
        "Bradesco Saúde",
        "Cabesp",
        "Saúde Caixa",
        "Care Plus",
        "CNU",
        "Cruz Azul",
        "Dix Amico",
        "Economus",
        "Funcesp",
        "Golden Cross",
        "Interclínicas",
        "Intermédica Notre Dame",
        "MAPFRE",
        "Porto Seguro",
        "Life Empresarial",
        "LINCX",
        "Medial",
        "Metrus",
        "Omint",
        "One Health",
        "Pasa",
        "Postal Saúde",
        "Prevent Sênior",
        "PROASA",
        "Seguros Unimed",
        "Next Seisa",
        "Sompo Saúde",
        "Sulamérica",
        "Vale Saúde",
      ],
      specialities: [
        "Clínica Médica",
        "Ortopedia Geral",
        "Psicologia",
        "Dermatologia",
        "Pediatria",
        "Endocrinologia",
        "Geriatria",
      ],
    },
    {
      name: "Hospital Albert Sabin",
      address: {
        addressLine: "Rua Brigadeiro Gavião Peixoto, 123 - Lapa",
        city: "São Paulo",
        state: "SP",
      },
      type: "private",
      medicalInsurance: [
        "Allianz",
        "APCEF/SP",
        "Bradesco Saúde",
        "Cabesp",
        "Care Plus",
        "Central Nacional Unimed",
        "CET",
        "Cruz Azul",
        "Funcesp",
        "Gama Saúde",
        "Golden Cross",
        "Intermédica Notre Dame",
        "Life Empresarial",
        "MAPFRE",
        "Mediservice",
        "PLASAC",
        "Porto Seguro",
        "Santamália",
        "São Cristóvão",
        "SBC",
        "Sepaco",
        "Sindicato Das Borrachas",
        "Sompo Saúde",
        "Sulamérica",
        "Seguros Unimed",
      ],
      specialities: [
        "Arritmologia",
        "Bucomaxilo",
        "Cardiologia",
        "Cirurgia Cardíaca",
        "Cirurgia Geral",
        "Cirurgia Plástica",
        "Clínica Geral",
        "Dermatologia",
        "Endocrinologia",
        "Fisioterapia",
        "Gastroenterologia",
        "Ginecologia",
        "Hematologia",
        "Neurocirurgia",
        "Neurologia Clínica",
        "Nutrologia",
        "Oftalmologia",
        "Oncologia Clínica",
        "Ortopedia Geral",
        "Otorrinolaringologia",
        "Pneumologia",
        "Proctologia",
        "Psiquiatria",
        "Urologia",
        "Vascular",
      ],
    },
    {
      name: "Hospital e Maternidade Metropolitano - Clínica Médica",
      address: {
        addressLine: ": Rua Marcelina, 513 - Vila Romana, São Paulo",
        city: "São Paulo",
        state: "SP",
      },
      type: "private",
      medicalInsurance: [
        "Allianz",
        "Amil Saúde",
        "Abet",
        "ASSEFAZ",
        "Afresp",
        "ASSIST CARD",
        "Bradesco Saúde",
        "Cruz Azul",
        "Care Plus",
        "Economus",
        "Funcesp",
        "Golden Cross",
        "Interclínicas",
        "MAPFRE",
        "Sompo Saúde",
        "Porto Seguro",
        "Sulamérica",
        "Seguros Unimed",
        "AXA – PORTOMED",
        "ASUNESP",
        "CABERJ",
        "CAMPOS SALLES",
        "CEMO",
        "Central Nacional Unimed",
        "CRYOVAC",
        "Gama Saúde",
        "GEAP Saude",
        "HASP",
        "IMAGINE",
        "Life Empresarial",
        "MARINHA BRASIL",
        "MAURICIO SOUSA",
        "Mediservice",
        "MEKNES",
        "Metrus",
        "MONDIAL",
        "Intermédica Notre Dame",
        "Omint",
        "PETROBRÁS",
        "Postal Saúde",
        "PROASA",
        "REAL EXPRESSO",
        "TEMPO ASSIST",
        "Unimed Fesp",
        "VOITH",
      ],
      specialities: [
        "Cardiologia",
        "Clínica da Dor",
        "Clínica Geral",
        "Coloproctologia",
        "Gastro Clinico",
        "Ginecologia",
        "Obstetrícia",
        "Hematologia",
        "Infectologia",
        "Mastologia",
        "Neurocirurgia",
        "Neuroendovascular",
        "Neurologia Clínica",
        "Obstetrícia",
        "Oncologia Clínica",
        "Ortopedia de Coluna",
        "Ortopedia de Ombro",
        "Ortopedia de Pé",
        "Ortopedia Geral",
        "Ortopedia Infantil",
        "Ortopedia Quadril",
        "Otorrinolaringologia",
        "Pediatria",
        "Urologia",
      ],
    },
  ];

}
